GET http://facpoc.titan/mibservice/health
###
GET http://facpoc.titan/facservice/health
###
GET http://facpoc.titan/mibhubservice/health
###
GET http://facpoc.titan/caseservice/health
###
GET http://facpoc.titan/correspondenceservice/health
### MIB => HUB
GET http://facpoc.titan/fac/SubmitMib
### Correspondence => Decision
GET http://facpoc.titan/fac/FacCaseDecision
### Fac Case Processor => Case
GET http://facpoc.titan/fac/SubmitCase

###
POST http://facpoc.titan/fac/PostMib 
Content-Type: application/json

{
    "FirstName": "Joe",
    "LastName": "Mope",
    "Dob": "12/1/2000"
}
### Fac Case Processor => Case
GET http://localhost:4003/fac/SubmitCase
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiR0FNRVJQQ1xcdnNpbW8iLCJleHAiOjE2MDM1NzEzMTksImlzcyI6IlhYWFgiLCJhdWQiOiJYWFhYIn0.b_iZz5GDLCg3vRSQGeQNvVWS7F8PV1AE9UfV-0RC824
###
http://localhost:4003/fac/FacCaseDecision
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiR0FNRVJQQ1xcdnNpbW8iLCJleHAiOjE2MDM2Mzc2ODksImlzcyI6IlhYWFgiLCJhdWQiOiJYWFhYIn0.LzFQgAVS4gqy69afhtZ8O2JfHFUTgeZs0JWXz0YQybI


