apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubservice
  namespace: fac
spec:
  selector:
    matchLabels:
      app: hubservice
  replicas: 1
  template:
    metadata:
      labels:
        app: hubservice
    spec:
      containers:
        - name: hubservice-pod
          image: vsimone67/hubservice:latest
          imagePullPolicy: 'Always'
          ports:
            - name: http
              containerPort: 80
          env:
            - name: 'appdirectory'
              value: '/app/settings/'
          volumeMounts:
            - name: configs
              mountPath: '/app/settings'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 360
      volumes:
        - name: configs
          projected:
            sources:
              - configMap:
                  name: appsettings-hubservice
              - secret:
                  name: appsettings-secret-hubservice
---
apiVersion: v1
kind: Service
metadata:
  name: hubservice-svc
  namespace: fac
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: hubservice
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: hubservice-route
  namespace: fac
spec:
  entryPoints:
    - web
  routes:   
    - match: Host(`facpoc.titan`) && PathPrefix(`/mibhub`)
      kind: Rule
      services:
        - name: hubservice-svc
          port: 80
    - match: Host(`facpoc.titan`) && PathPrefix(`/facdecision`)
      kind: Rule
      services:
        - name: hubservice-svc
          port: 80
    - match: Host(`facpoc.titan`) && PathPrefix(`/faccase`)
      kind: Rule
      services:
        - name: hubservice-svc
          port: 80
    - match: Host(`facpoc.titan`) && PathPrefix(`/mibhubservice/health`)
      kind: Rule
      services:
        - name: hubservice-svc
          port: 80
      middlewares:
        - name: st-healthcheck
    - match: Host(`facpoc.titan`) && PathPrefix(`/mibhubservice/metrics`)
      kind: Rule
      services:
        - name: hubservice-svc
          port: 80
      middlewares:
        - name: st-metrics
