apiVersion: apps/v1
kind: Deployment
metadata:
  name: correspondenceservice
  namespace: fac
spec:
  selector:
    matchLabels:
      app: correspondenceservice
  replicas: 1
  template:
    metadata:
      labels:
        app: correspondenceservice
    spec:
      containers:
        - name: correspondenceservice-pod
          image: vsimone67/correspondenceservice:latest
          imagePullPolicy: 'Always'
          ports:
            - name: http
              containerPort: 80
          env:
            - name: 'appdirectory'
              value: '/app/settings/'
          volumeMounts:
            - name: configs
              mountPath: '/app/settings'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 360
      volumes:
        - name: configs
          projected:
            sources:
              - configMap:
                  name: appsettings-correspondenceservice
              - secret:
                  name: appsettings-secret-correspondenceservice
---
apiVersion: v1
kind: Service
metadata:
  name: correspondenceservice-svc
  namespace: fac
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: correspondenceservice
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: correspondenceservice-route
  namespace: fac
spec:
  entryPoints:
    - web
  routes:
    # - match: Host(`facpoc.titan`) && PathPrefix(`/PATHPREFIXHERE`)
    #   kind: Rule
    #   services:
    #     - name: correspondenceservice-svc
    #       port: 80
    # - match: Host(`facpoc.titan`)
    #   kind: Rule
    #   services:
    #     - name: correspondenceservice-svc
    #       port: 80
    - match: Host(`facpoc.titan`) && PathPrefix(`/correspondence/{catchall}`)
      kind: Rule
      services:
        - name: correspondenceservice-svc
          port: 80
    - match: Host(`facpoc.titan`) && PathPrefix(`/correspondenceservice/health`)
      kind: Rule
      services:
        - name: correspondenceservice-svc
          port: 80
      middlewares:
        - name: st-healthcheck
    - match: Host(`facpoc.titan`) && PathPrefix(`/correspondenceservice/metrics`)
      kind: Rule
      services:
        - name: correspondenceservice-svc
          port: 80
      middlewares:
        - name: st-metrics
