apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: st-healthcheck
spec:
  replacePath:
    path: /actuator/health
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: st-metrics
spec:
  replacePath:
    path: /actuator/metrics
