apiVersion: apps/v1
kind: Deployment
metadata:
  name: mibservice
  namespace: fac
spec:
  selector:
    matchLabels:
      app: mibservice
  replicas: 1
  template:
    metadata:
      labels:
        app: mibservice
    spec:
      containers:
        - name: mibservice-pod
          image: vsimone67/mibservice:latest
          imagePullPolicy: 'Always'
          ports:
            - name: http
              containerPort: 80
          env:
            - name: 'appdirectory'
              value: '/app/settings/'
          volumeMounts:
            - name: configs
              mountPath: '/app/settings'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: configs
          projected:
            sources:
              - configMap:
                  name: appsettings-mibservice
              - secret:
                  name: appsettings-secret-mibservice
---
apiVersion: v1
kind: Service
metadata:
  name: mibservice-svc
  namespace: fac
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: mibservice
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: mibservice-route
  namespace: fac
spec:
  entryPoints:
    - web
  routes:   
    - match: Host(`facpoc.titan`) && PathPrefix(`/mib/{catchall}`)
      kind: Rule
      services:
        - name: mibservice-svc
          port: 80
    - match: Host(`facpoc.titan`) && PathPrefix(`/mibservice/health`)
      kind: Rule
      services:
        - name: mibservice-svc
          port: 80
      middlewares:
        - name: st-healthcheck
    - match: Host(`facpoc.titan`) && PathPrefix(`/mibservice/metrics`)
      kind: Rule
      services:
        - name: mibservice-svc
          port: 80
      middlewares:
        - name: st-metrics
